In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

## Getting starting with Dataset

In [ ]:
# Read the given dataset
df = pd.read_csv("/kaggle/input/geeksforgeeks-youtube/gfg.csv")
df.head()

In [ ]:
df.describe()

## Check for Null Values in Dataset

In [ ]:
# Find if there is any NULL Value in dataset
df.isnull()

In [ ]:
df.isnull().sum()

## Remove the rows with Null Values

In [ ]:
df.dropna()
# As result we only have 1854 rows only out of 2091 rows.

## Get rid off from Null Values

In [ ]:
# Remove NULL Values from dataset
df = df.dropna()
df.head()

## Titles of Videos

In [ ]:
df['title']

## Find the Video with Specific Title

In [ ]:
title = "Python"

for i in df['title']:
    if title in i:
        print(i)

## Get Count of Videos with Specific Title

In [ ]:
title = "Python"
count = 0

for i in df['title']:
    if title in i:
        count += 1
        
print(count)

## Find the Video Links on Specific Title

In [ ]:
# Without using any inbuilt function
data = df.values   # Convert into an array

In [ ]:
title = 'Python'.lower()

for i in data:
    if(title in i[3].lower()):
        print(i[3],i[0])

## Total Views on all the Videos

In [ ]:
views = []
for i in df['views']:
    views.append(int(i.replace(',','')))
sum(views)

In [ ]:
# Make same change in original dataset
df['views'] = views
df

In [ ]:
df['views'].sum()

## Analysing Comments

In [ ]:
# Let's do some data pre-processing

df['comments']

# Again we have float values instead of integer value

In [ ]:
# Convert Float value of comments into Integer
comments = []

for i in df['comments']:
    comments.append(int(i))

In [ ]:
# Make some changes in original dataset

df['comments'] = comments
df

## Analysing Likes

In [ ]:
# Some Data preprocessing on Likes

df['likes']

In [ ]:
# Likes in dataset are in string, So we have to convert it in Integer 
# Another thing is some likes are in form of 'K' means in terms of 1000. This is also we have to convert into Integer

likes  = []
for i in df['likes']:
    if('K' in i):
        likes.append(int(float(i[:-1])) * 1000)
        
    else:
        likes.append(int(i))

In [ ]:
# It's time to make changes in original dataset
df['likes'] = likes
df

## Analysing Durantion of Video

In [ ]:
df['duration']

In [ ]:
# Time Duration in dataset are in string, So we have to convert it in Integer 
# Format of Time duration is [HH : MM : SS]
# Now we will convert it into Seconds.

duration = []
for i in df['duration']:
    time = i.split(',')
    
    sec = 0
    if len(time) == 1:                        # if Lenght of time is equal to 1
        if(i.split(' ')[1] == 'seconds'):
            sec += int(i.split(' ')[0])
        if(i.split(' ')[1] == 'minutes'):
            sec += (int(i.split(' ')[0]) * 60)
        if(i.split(' ')[1] == 'hour'):
            sec += (int(i.split(' ')[0]) * 3600)
            
        duration.append(sec)    
      
    sec = 0
    if len(time) == 2:                        # if Lenght of time is equal to 2
        if(time[0].split(' ')[1] == 'minutes'):
            sec += int(time[0].split(' ')[0]) * 60
        if(time[0].split(' ')[1] == 'hour'):
            sec += int(time[0].split(' ')[0]) * 3600
        if(time[1].strip().split(' ')[1] == 'seconds'):
            sec += int(time[1].strip().split(' ')[0])
        if(time[1].strip().split(' ')[1] == 'minutes'):
            sec += int(time[1].strip().split(' ')[0]) * 60
            
        duration.append(sec)
    
    sec = 0
    if(len(time) == 3):                        # if Lenght of time is equal to 3
        #print(time)
        if(time[1].strip().split(' ')[1] == 'hour' or 'hours'):
            sec += int(time[1].strip().split(' ')[0]) * 3600
        if(time[1].strip().split(' ')[1] == 'minutes'):
            sec += int(time[1].strip().split(' ')[0]) * 60
        if(time[1].strip().split(' ')[1] == 'seconds'):
            sec += int(time[1].strip().split(' ')[0])
            
        duration.append(sec)

In [ ]:
# It's time to make changes in original dataset

df['duration'] = duration
df